### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by francipvb** [dworkin/dgd#23]
Hello,

Do you have plans to support Docker? If not, I want to do a little contribution regarding this.

Cheers,

**Comment by dworkin** [comment]
I've thought about DGD and Docker, but I haven't been persuaded yet that they are a good match.

A Docker image would provide a sandbox, and a pre-compiled binary of DGD.  DGD has no external dependencies, so there is little point in providing a custom environment.

DGD is also designed from the ground up to be upgradable without downtime, via hotbooting.  That can't be done via a Docker image upgrade.  What you could do is put the compiler inside the Docker image, but now you suddenly have a huge image to maintain, and you also have to work out a way to pull in the latest DGD source code to compile from; moreover, the state of the Docker image can now change. You could install Docker image A, let it upgrade DGD to A', and then attempt to upgrade the Docker image to B, resulting in a failure because the external mudlib matches A'.

The sandbox would be useful, but some of the other features of Docker seem to work against DGD's design.

**Comment by francipvb** [comment]
Hello,

Yes, you are right. However this may be a good way of doing automated checks in cloud environment at mudlib level. The dev just have to change a version variable of dgd version to run tests against it without compiling and running dgd.

Another scenario is user testing of mudlibs.

**Comment by dworkin** [comment]
Sorry for being out of the loop for a while.  If you want to maintain a docker image of DGD, go ahead.

**Comment by Blain20** [comment]
Just out of curiosity, what happened to the github versions of DGD after 1.6.8?

**Comment by dworkin** [comment]
Has something happened to them?

I'm not sure what this has to do with docker images.

**Comment by shentino** [comment]
> Just out of curiosity, what happened to the github versions of DGD after 1.6.8?

From what I can tell they're still being tagged in the repository, see "git tag"

I'm not exactly sure how github does "official" releases if that's what you're talking about but I install/build DGD straight out of the repo anyway.

**Comment by Blain20** [comment]
I replied to an old email about docker and it was linked to that thread.  I'm seeing 1.6.8 as the latest version in the master branch, that's all.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Blain20** [comment]
I haven't been on github in a while and was expecting to see the later releases right on front of me instead of having to go to the releases section to get them.  I rediscovered them.  You can close this if it's supposed to be closed. Sorry for the confusion.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by dworkin** [comment]
This doesn't seem to be going anywhere. If @francipvb wants to maintain a docker image, he can reopen the issue.

**Comment by dworkin** [comment]
@francipvb There may be a use for a docker container image that we didn't consider yet. DGD now has a bunch of extensions that are very useful (JIT compiler, gzip compression, crypto functionality) which are very useful but which are more complicated to set up than plain DGD.
What a container could provide is a build environment for DGD and all of those extensions. The container would not be a typical microservice, but a persistent container in which DGD is updated, compiled, and where it hotboots into the next version, all without taking the server down, and without restarting the container. JIT compiled objects would be cached inside the container. The mudlib would not reside inside the container.

**Comment by francipvb** [comment]
Hello,

I will try to do some coding regarding this at this weekend.

Cheers, 

-- 
Cuando tus fuerzas terminan, las de mi Dios comienzan.

**Comment by dworkin** [comment]
I've included rudimentary container support in the latest update.  Let me know what you think.
