### ISSUE TITLE
Telnet treats SGA as on by default

### ISSUE THREAD

**Issue by nyankers** [dworkin/dgd#58]
Per [RFC858](https://datatracker.ietf.org/doc/html/rfc858), the default behavior should be that SGA is off and therefore IAC GA should be sent after every prompt.

Currently, dgd does the opposite of this. The default behavior is that SGA is on.

**Comment by nyankers** [comment]
Created a pull request to hopefully help highlight what's going on in code: #59

**Comment by rubyFeedback** [comment]
Good old telnet ... reminds me of the 1990s. We accessed MUDs via
green-font-colour on black background computers from the university.
It even took me a while to figure out that I could echo-see my own 
commands!

In later years I switched to zmud and then tintin eventually - the latter
mostly because it was simple. I kept all my aliases in a yaml file and
autogenerated valid aliases via ruby. I think the young(er) whippersnappers
today may not even use telnet anymore. Thus, they can never experience
the joy and nostalgia of retro gaming... :)
