### ISSUE TITLE
Unallocated int becomes nil in switch()

### ISSUE THREAD

**Issue by nyankers** [dworkin/dgd#67]
The following code will return `nil` rather than `0`:

```
#include <type.h>

mixed test()
{
	int x;
	switch (2) {
		case 1:
			x = 42;
			break;

		default:
			return x;
	}
}
```

The code is pretty self-demonstrating for when this happens: a local `int` never uninitialized, the program goes into a `switch()` statement that has some `case` which initializes it, but goes down a later `case` statement which uses it uninitialized.

The expectation is that it should return 0, which it does if it's ever assigned (even to `0`), if the assignment `x = 42;` is removed, or even if the `case 1:` and `default:` code segments are swapped.

Even though this bug seems very specific when it occurs, `x` doesn't have to be returned to have a `nil` value. In my local purpose for this code pattern, I was using it to make an array, and was confused why I was getting `nil` values.

**Comment by dworkin** [comment]
You are raking them up today.  I won't have time to look at this until later.

**Comment by nyankers** [comment]
Aha, there's no rush (lots of easy workarounds for this bug anyway!). I'd have taken a look at it myself but I wanted to finish the thing I was working on that lead me to finding it. :)

I swear I'm coding perfectly normal LPMud stuff as I find these! The other one was safety net code to make sure I can't heal someone to death along with some demo code that tried, and this was a bug in parsing crafting component strings (I'd meant to initialize it to 1 so "copper" and "1x copper" work the same, but forgot to add that in and saw `nil`s appearing where only an `int` should have gone).

**Comment by nyankers** [comment]
The issue seems due to the logic for checking if a variable needs initialized or not. This logic seems to know how to handle conditional statements, but not how to handle switch statements.

I've created pull request #68 to show a dumb solution to highlight the problem area, though as the comments there suggest, it really just disregards variable initialization in switch statements. Given case statements can go virtually anywhere (besides nested in another switch statement), I'm not sure fixing this properly would be easy without some serious reconsideration into that logic.

**Comment by dworkin** [comment]
Yes, I completely overlooked switch statements when I wrote this.

DGD is composed of two types of code. Some of it is ultra-competent code to support, for example, atomic functions, which takes a very solid foundation with a lot of layers on top to get it all to work just right. But there is also code which just barely does what it is supposed to do, usually because doing it the proper way would be too complex and slow. Most of the compiler is like that, since it is important that the compiler is lightning-fast.
The code here is of the latter kind. I will have to extend it with other code that just barely works. :)

**Comment by nyankers** [comment]
Yeah. I'm not sure I could come up with such a solution here, given how chaotic case statements can get. In theory, you could do some breadth-first search in the code to see if you can find even a single branching path that uses the variable without assigning it... but that might be a bit much.

I think at that point, I'd personally look at storing local variable types somewhere, and initializing them like how args get initialized already. But you're a bit more clever than I am at this stuff, so maybe you can sort it out better. ^^

I did find it a bit funny that locals do get initialized, just always to `nil`.

Actually, since they always get initialized to `nil`, is there any point in keeping track of whether non-int/floats get used or not? That feels a bit redundant to me - or perhaps the redundancy is initializing them without any byte code telling the interpreter to do so.

**Comment by dworkin** [comment]
Should be fixed by cdcdf2bb45b75be04dd087333f808b8682768dac.

**Comment by nyankers** [comment]
Looks like it's fixed to me, thanks. ^^

**Comment by dworkin** [comment]
There was a lot to fix. Apart from not detecting uninitialized access within a switch, there were a lot of false positives because it only really worked for variables declared in the current compound statement, not for variables declared outside.

Most of this is now obsolete since the JIT compiler solves the same problem better, but in the end the runtime cost is low, the fix is small and the code becomes more clear, so I decided to keep it.

**Comment by dworkin** [comment]
There was another failure case:
```
mixed test()
{
    int i;

    do {
        break;
        i = 1;
    } while (0);
    return i;
}
```
which is handed by 1edd1755cf57bd6c2f2880596085724e4a86ac14.

**Comment by nyankers** [comment]
Ah, I didn't even think to check that one. Nice catch. ^^
